### ISSUE TITLE
Issue parsing DSL after upgrade due to scripting engine missing 

### ISSUE THREAD

**Issue by juanrferia** [structurizr/dsl#101]
Hello,

I've recently upgraded the library _com.structurizr:structurizr-dsl_ from 1.14.0 to 1.17.0 and, after that, I'm facing an issue when parsing DSL model which include an script:

```
java.lang.RuntimeException: Could not load a scripting engine for extension "groovy"
        at com.structurizr.dsl.ScriptDslContext.run(ScriptDslContext.java:26)
        at com.structurizr.dsl.InlineScriptDslContext.end(InlineScriptDslContext.java:41)
        at com.structurizr.dsl.StructurizrDslParser.endContext(StructurizrDslParser.java:798)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:162)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:122)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:97)
        at com.structurizr.dsl.WorkspaceParser.parse(WorkspaceParser.java:65)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:358)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:122)
```
Does that upgrade have additional requirements I missed?

Thanks!

**Comment by juanrferia** [comment]
BTW, I can see I can also face the issue when upgrading to 1.15.0

**Comment by simonbrowndotje** [comment]
If you're using the DSL library as a Maven dependency, you'll now need to add an additional dependency for any compatible scripting languages you want to use ... [for example](https://github.com/structurizr/cli/blob/master/build.gradle#L23).

**Comment by juanrferia** [comment]
Thanks for the quick feedback. Working! :)
