### ISSUE TITLE
!constant not expanded in views properties

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#168]
The following
```
    views {
        !constant SEQUENCE_DIAGRAMS "plantuml.sequenceDiagrams true"
        properties {
            "plantuml.includes" "extra_styles.puml"
            "c4plantuml.tags" "true"
            "plantuml.legend" "false"
            ${SEQUENCE_DIAGRAMS}
        }
    }
```
triggers the error
```
com.structurizr.dsl.StructurizrDslParserException: Expected: <name> <value> at line 236: ${SEQUENCE_DIAGRAMS}
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:785)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:125)
        at com.structurizr.cli.export.ExportCommand.run(ExportCommand.java:126)
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:77)
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:112)
```

Same effect if I enclose the constant in double quotes.

**Comment by dgutson** [comment]
What does 'within a token' mean?
