### ISSUE TITLE
Can't apply two or more styles tags

### ISSUE THREAD

**Issue by ziweiD** [structurizr/dsl#204]
Hello, I'm playing around with structurizr and find that I got the following error when I try to apply two style tags to one container:
```
com.structurizr.dsl.StructurizrDslParserException: Unexpected tokens at line 2: container1 = container "Container1" "description" "technology" "color","shape"
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:761)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:125)
        at com.structurizr.cli.PushCommand.run(PushCommand.java:121)
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:77)
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:112)
```
Here is my workspace dsl:
```
workspace "example" "workspace" {
    container1 = container "Container1" "description" "technology" "color","shape"

    views {
        container example {
            include *
            autolayout lr 
        }

        styles {
            element "color" {
                background #664fa6
                color #ffffff
            }

            element "shape" {
                shape RoundedBox
            }
        }
    }
}
```
Could you please help check? Thanks.

**Comment by simonbrowndotje** [comment]
Your DSL is invalid for a number of reasons, which is why you're getting the `Unexpected tokens at line 2` message:

1. Missing `model` block.
2. `container` can only be used within a `softwareSystem` block.

Here's a valid version:

```
workspace "example" "workspace" {

    model {
        example = softwaresystem "example" {
            container1 = container "Container1" "description" "technology" "color,shape"
        }
    }

    views {
        container example {
            include *
            autolayout lr 
        }

        styles {
            element "color" {
                background #664fa6
                color #ffffff
            }

            element "shape" {
                shape RoundedBox
            }
        }
    }
}
```

You can also do this:

```
workspace "example" "workspace" {

    model {
        example = softwaresystem "example" {
            container1 = container "Container1" "description" "technology" {
                tags "color,shape"
            }
        }
    }

    views {
        container example {
            include *
            autolayout lr 
        }

        styles {
            element "color" {
                background #664fa6
                color #ffffff
            }

            element "shape" {
                shape RoundedBox
            }
        }
    }
}
```
