### ISSUE TITLE
!impliedRelationships example usage

### ISSUE THREAD

**Issue by rvinzent** [structurizr/dsl#78]
I tried using the [`!impliedRelationships`](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#impliedrelationships) flag at the workspace level and ran into an "unexpected tokens" issue. It would help if there was an example of proper syntax somewhere because at this point because I can't tell what I'm doing wrong.

```
workspace "Test" {
    !impliedRelationships true

    model {
        softwareSystem
    }
}
```

```
com.structurizr.dsl.StructurizrDslParserException: Unexpected tokens
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:670)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:119)
        at com.structurizr.cli.ExportCommand.run(ExportCommand.java:113)
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:48)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:93)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
com.structurizr.dsl.StructurizrDslParserException: Unexpected tokens at line 2: !impliedRelationships true
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:683)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:119)
        at com.structurizr.cli.ExportCommand.run(ExportCommand.java:113)
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:48)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:93)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

**Comment by simonbrowndotje** [comment]
The docs reference the new version of the DSL, which is the processed of being released. Try `impliedRelationships` (without the leading `!` character).

**Comment by simonbrowndotje** [comment]
v1.13.0 of the DSL and CLI have been released now, so the docs are now in sync again.
